### PR TITLE
blitz.lua game upload

### PR DESCRIPTION
**Pull request by simlx**

### CODE REVIEW

**Comment by ukgamer** [comment]
Some issues I've spotted:
The game is very difficult to play at high framerates - I don't think you're using FrameTime to scale the movement?
The plane clips through the tops of buildings
Are the clouds supposed to be wobbling?

**Comment by simlx** [comment]
Ok, so i added the FrameTime() function to all the movement and such, i noticed some speed differences aswell just not as much because of the low difference in FPS but it should be fixed now.
The plane shouldn't be clipping anymore and the cloud wobble was wanted but i removed it because it looks better without

**Comment by jule14** [comment]
poggers

**Comment by ukgamer** [comment]
The game is now running far too slow when I'm at a steady ~160FPS. Capping my framerate to 30 causes the plane to move at more reasonable speed, so it's not scaling by frame time correctly. I also noticed the bomb does not collide with the buildings until the top left of the bomb intersects with a building. Are you using the collision library?

The marquee is also not scaling correctly - the marquee resolution was recently increased so you will either need to increase the size of your art or make it take into account the MARQUEE_WIDTH/MARQUEE_HEIGHT:

gmod_2020-07-07_01-20-50_PoliteNorthernseahorse 1

**Comment by simlx** [comment]
fps, marquee art is fixed

**Pull request merged**
